# Generated by Django 4.0.4 on 2022-06-22 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('IdA', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('SatutVaccinal', models.CharField(max_length=25)),
                ('Sterilization', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=25)),
                ('Prenom', models.CharField(max_length=25)),
                ('Cin', models.CharField(max_length=8, unique=True)),
                ('SalaireMensuelle', models.FloatField()),
                ('Logement', models.CharField(max_length=25)),
                ('Jardin', models.BooleanField()),
                ('SituationFamiliale', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('phoneNumber', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CatAnimal',
            fields=[
                ('IdCat', models.AutoField(primary_key=True, serialize=False)),
                ('Categorie', models.CharField(blank=True, choices=[('CHAT', 'Chat'), ('CHAT', 'Chien'), ('Oiseau', 'Oiseau')], max_length=50)),
                ('IdA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.animal')),
            ],
        ),
    ]
