# Generated by Django 4.0.4 on 2022-06-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Adopteur',
        ),
    ]
