# Generated by Django 4.0.4 on 2022-06-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_person_adopteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
