# Generated by Django 4.0.4 on 2022-06-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_animal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='Categorie',
            field=models.CharField(blank=True, choices=[('CHAT', 'Chat'), ('CHAT', 'Chien'), ('Oiseau', 'Oiseau')], max_length=50),
        ),
        migrations.DeleteModel(
            name='CatAnimal',
        ),
    ]
