# Generated by Django 4.0.4 on 2022-06-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_satutvaccinal_animal_statutvaccinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Categorie',
            field=models.CharField(blank=True, choices=[('CHAT', 'Chat'), ('CHIEN', 'Chien'), ('Oiseau', 'Oiseau')], max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='StatutVaccinal',
            field=models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='Sterilization',
            field=models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=50),
        ),
    ]
