# Generated by Django 4.0.4 on 2022-06-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_animal_categorie_alter_animal_statutvaccinal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopteur',
            name='IdA',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='Adopte',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='Photo',
            field=models.ImageField(upload_to='static/images/animals/'),
        ),
    ]
