# Generated by Django 4.0.4 on 2022-06-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_adopteur_ida_animal_adopte_alter_animal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopteur',
            name='Cin',
            field=models.CharField(max_length=8),
        ),
    ]
